import os
import json
import time  
import milestone2  
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

# --- CONFIGURATION ---
# Defines the output directory for the final synthesized review documents.
FINAL_REPORTS_DIR = "final_reports"

# Initialize the LLM. 
# Note: Using gemini-2.5-flash for optimal performance in synthesis. 
# Temperature is set to 0.3 to maintain academic tone while allowing slight creative variance for natural writing.0-10(RANDOMESS/CREATIVITY AT 10 AND STRICTLY PROBABILISTIC AND STATISITICAL AT 0)
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.3)#1.5 MODEL for better api exhaustion management on free tier, 2.5 for better synthesis quality

def generate_section(section_name, context, instructions):
    """
    Generates automated section drafts using AI synthesis.
    This modular function acts as the core writing engine, allowing us to dynamically
    generate distinct sections (Abstract, Methods, Results) using the same pipeline.
    """
    # CRITICAL FIX: Convert JSON data to a string and double-escape curly braces {{ }}.
    # This prevents LangChain's prompt template parser from confusing JSON syntax with prompt variables,
    # avoiding KeyError crashes during execution.
    context_str = json.dumps(context).replace("{", "{{").replace("}", "}}")
    
    # Constructing a structured prompt to enforce an academic persona and strict constraint adherence.
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are an expert academic writer. Produce structured writing for the {section_name} section of a systematic review."),
        ("human", "Research Data Context:\n{context_data}\n\nStrict Instructions: {instructions}")
    ])
    
    # Create the LCEL (LangChain Expression Language) chain and invoke it
    chain = prompt | llm
    return chain.invoke({
        "section_name": section_name,
        "context_data": context_str,
        "instructions": instructions
    }).content

def run_milestone_3_pipeline(topic, count):
    """
    Orchestrates the Milestone 3 workflow: taking extracted data and synthesizing a final draft.
    """
    print("\n" + "="*50)
    print("PHASE 3: WRITING & SYNTHESIS (Milestone 3)")
    print("="*50)

    # Step 1: Trigger the predecessor pipelines (M1: Download -> M2: Extract & Compare)
    milestone2.run_milestone_2_pipeline(topic, count)
    
    # Step 2: Load the structured analysis data generated by Milestone 2
    safe_topic = milestone2.milestone1.sanitize_filename(topic)
    data_path = os.path.join(milestone2.PROCESSED_DIR, safe_topic, "processed_data.json")
    
    with open(data_path, 'r') as f:
        data = json.load(f)

    print(f"\n[SYNTHESIS] Generating final review sections for '{topic}'...")

    # Step 3: Sequentially generate the required academic sections.
    # We pass specific constraints (like word counts) directly into the prompt.
    
    # 3a. Abstract (Requires synthesis of cross-paper themes)
    print(" -> Generating Abstract...")
    abstract = generate_section("Abstract", data["cross_paper_analysis"], "Strictly limit the response to 100 words or less.")
    
    # RATE LIMITING STRATEGY: Pausing execution to avoid triggering HTTP 429 (Resource Exhausted) errors
    # on the API free tier, ensuring pipeline stability during sequential generation.
    print(" -> [Waiting 5 seconds to respect API rate limits...]")
    time.sleep(5)

    # 3b. Methods Comparison (Focuses on methodology differences/overlaps)
    print(" -> Generating Methods Comparison...")
    methods = generate_section("Methodology Comparison", data["cross_paper_analysis"], "Compare and synthesize the methodologies used across the papers.")

    print(" -> [Waiting 5 seconds to respect API rate limits...]")
    time.sleep(5)

    # 3c. Results Synthesis (Focuses on granular, individual paper findings)
    print(" -> Generating Results Synthesis...")
    results = generate_section("Results Synthesis", data["individual_papers"], "Synthesize the primary outcomes and key findings into a unified narrative.")

    # Step 4: Automated APA Reference Formatting
    # Iterates through the processed dataset to construct a standardized bibliography.
    references = "## References (APA)\n"
    for paper in data["individual_papers"]:
        clean_title = paper['file_name'].replace('.pdf', '')
        references += f"- {clean_title}. (2026). Retrieved from Automated Research Pipeline.\n"

    # Step 5: Document Assembly
    # Combines all generated sections into a cohesive Markdown document.
    report_content = f"# Systematic Review: {topic}\n\n## Abstract\n{abstract}\n\n## Methods\n{methods}\n\n## Results\n{results}\n\n{references}"
    
    # Ensure the output directory exists before writing
    if not os.path.exists(FINAL_REPORTS_DIR): 
        os.makedirs(FINAL_REPORTS_DIR)
        
    # Step 6: Save the final output dataset/report to disk
    save_path = os.path.join(FINAL_REPORTS_DIR, f"{safe_topic}_report.md")
    with open(save_path, "w", encoding='utf-8') as f:
        f.write(report_content)
        
    print(f"\n[SUCCESS] Final draft generated and saved to: {save_path}")
    return report_content

# Execution block: Only runs if the script is executed directly (not imported)
if __name__ == "__main__":
    topic, count = milestone2.milestone1.get_user_input()
    if topic and count:
        final_draft = run_milestone_3_pipeline(topic, count)
        print("\n--- GENERATED DRAFT PREVIEW ---")
        print(final_draft[:500] + "\n... [Output truncated for terminal preview] ...")